### ISSUE TITLE
Useless mixInChain() code

### ISSUE THREAD

**Issue by koresar** [ericelliott/stampit#42]
@ericelliott The `mixInChain` function looks, feels and behaves exactly as `mixIn` function. Sometimes we are using `mixInChain` to merge methods, but sometimes - `mixIn`.
Why?
I assume the `mixInChain` is redundant. Is it okay if I remove it?

**Comment by ericelliott** [comment]
Nope. I wrote it to make tests pass. I believe mixIn guards for against the prototype. `mixInChain` flattens the prototype chain. I wrote it a long time ago, so I'm not certain, but I think if you swap them out, tests will break.

**Comment by koresar** [comment]
Tests pass if I use mixIn instead of mixInChain. :)

**Comment by ericelliott** [comment]
Interesting. Maybe we changed something since I wrote it and it's no longer necessary. =)

**Comment by koresar** [comment]
I'll submit a PR to v2_0 branch.

**Comment by ericelliott** [comment]
:+1:

**Comment by koresar** [comment]
I was wrong. `mixInChain` is the same as `mixIn` **but** it copies also properties from parent prototype chain. Thus is the name of function.

However, there are no comments. Reading code becomes time expensive (I'll fix that).
Also the only unit test for this function named `stampit.compose() with inheritance`, whereas mixInChain used for methods only. I'll give it a better name, like 'methods must mix in prototype chain'.

**Comment by koresar** [comment]
The `mixInChain` copies not only methods but also properties. As the result a bit of confusion takes place. The `stampit(methods)` and `stamp.methods(methods)` shallow copy state (if present) of the given object. This is no good because our stamps should be immutable.

@ericelliott is it by design?

**Comment by koresar** [comment]
Two ways to solve this:
1. Mix in functions only.
2. _Merge_ in everything (assumes deep cloning).

**Comment by ericelliott** [comment]
> The mixInChain copies not only methods but also properties. As the result a bit of confusion takes place. The stampit(methods) and stamp.methods(methods) shallow copy state (if present) of the given object. This is no good because our stamps should be immutable.

This is by design, so that you can have "class variables" such as instance counters. If we remove that capability, we'll definitely break a feature that people are using in production.

**Comment by ericelliott** [comment]
IMO, a better way to do things like instance counters is to add each new instance to a collection (which can be done even with immutable data structures).

**Comment by koresar** [comment]
So, option 2. Right? Deep clone state of the `methods` argument?

**Comment by koresar** [comment]
Object counter better implementation:
```js
var accountable = (function() {
  var number = 0;
  return stampit().enclose(function(){ 
    number++;
    this.getObjectCount = function () { return number; };
  })
})();
```

Combine this with your stamp and then you can control the number of objects created. :) Same way you can collect all references.

**Comment by koresar** [comment]
*Chain mixing the `methods` argument is a bad idea.* And here is why.

1. The `mixInChain` uses `mout/object/forIn`. All properties except the list of ES5 predefined 7 (like `toString`, `hasOwnProperty`, etc) are being copied over to the stamp.
1.1. If someone would extend `Object` then we'll be copying these extra function all the time for each stamp and new object.
1.1. ES6/ES7 might introduce [new Object.prototype methods](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object). These might be copied to each stamp too and we don't want the overhead.

2. I have never used anything else besides the flat JS objects as `methods` parameter. I doubt other people pass there complex objects.

3. The **hidden** behaviour of `methods()` function manipulates the state of each object created from the stamp.
3.1. The function named `methods()` should not add any state. Confuses a lot.
3.2. Objects created from a stamp should not share state. Otherwise people might change all the objects unintentionally by changing single value.
3.3. If someone would like to share state between some objects he must do that **explicitly** (see workaround code above).


I recommend we copy only **own functions** of the `methods` argument. Thus we will:
1. avoid all the potential problems described above;
2. make stamps immutable.

**Comment by ericelliott** [comment]
I'm pretty sure that very common use cases like trying to inherit from EventEmitter with convertConstructor would break without `mixInChain`. Basically any constructor that inherits through the prototype chain will break if we remove `mixInChain`. I think enabling Stampit to work with commonly used constructors from Node and other popular libraries pretty much trumps any of the concerns you mentioned.

Wouldn't you agree?

**Comment by ericelliott** [comment]
If you're really concerned we can explicitly guard against inheriting from the base `Object.prototype`, but we still need to be able to inherit from parent prototypes for compatibility with old classical inheritance style libraries.

**Comment by koresar** [comment]
Then `mixInChain` should be used for `convertConstructor` only. The `methods()` should be methods only.

**Comment by ericelliott** [comment]
Good point. Does it break any tests?

**Comment by koresar** [comment]
Yes. See [above](https://github.com/ericelliott/stampit/issues/42#issuecomment-70185556).

**Comment by ericelliott** [comment]
Change `'stampit.compose() with inheritance'` so that it uses `.convertConstructor()` to create the `sn` stamp. That test should still pass.

**Comment by koresar** [comment]
Correct. Will do. Thank you.

**Comment by ericelliott** [comment]
Thank you! =)

:+1:

**Comment by koresar** [comment]
Done with #48.
