### ISSUE TITLE
obj instanceof stamp

### ISSUE THREAD

**Issue by koresar** [ericelliott/stampit#44]
My colleagues complain that they cannot ducktype objects. One of them really insisted on the syntax:
```js
var Stamp = stampit(bla, bla, bla);

// Somewhere deep inside the app
obj = Stamp(ble, ble, ble);
if (obj instanceof Stamp) {
 // true
}
```

I implemented it. This would works too.
```js
obj = new Stamp(ble, ble, ble);
if (obj instanceof Stamp) {
 // true
}
```

This is easily achievable without breaking the existing API and without performance penalties. I actually already implemented this on my machine.

Sounds like good feature?

**Comment by koresar** [comment]
Here are the changes. Please, take a look at the three new unit tests.
https://github.com/ericelliott/stampit/compare/v2_0...instanceof

All the tests pass.

**Comment by ericelliott** [comment]
Don't trust `instanceof` in JavaScript. It does not do what the name implies that it does. It does not work across execution contexts. It doesn't work if the `fn.prototype` property gets changed after the object was instantiated. Basically, it's a completely broken concept in JS. It doesn't remotely make the guarantees that Java people expect it to make.

Never require `new` (or suggest it, or imply that consumers can use it).

http://ericleads.com/2013/01/javascript-constructor-functions-vs-factory-functions/
http://ericleads.com/2012/09/stop-using-constructor-functions-in-javascript/
https://medium.com/javascript-scene/the-two-pillars-of-javascript-ee6f3281e7f3

**Comment by ericelliott** [comment]
I appreciate the effort and enthusiasm, but I'm not going to encourage users to make mistakes.

**Comment by koresar** [comment]
I see.
Any recommendations on how to ducktype objects made by particular stamp?

**Comment by ericelliott** [comment]
Yeah. Ducktype. Checking `instanceof` is the opposite of ducktyping.

Ducktyping means that you check the object instance, and if it has the stuff you expect to have, you just assume it's a compatible type and use it.

**Comment by FredyC** [comment]
Found a reference to this on gitter and I am just curious if duck typing is sort of a same thing as type checking? I mean there things like [flow-runtime](https://github.com/codemix/flow-runtime) which can turn static types to runtime checks.

**Comment by koresar** [comment]
Looking at the amount of code `flow-runtime` has and at the the [code example](https://codemix.github.io/flow-runtime/#/) it's probably implemented somehow different to just `instanceof` proposed above.

**Comment by FredyC** [comment]
I don't care about `instanceof`, I agree with @ericelliott that it's misleading. The `flow-runtime` just turns static typings into runtime code.

```js
const MyStamp = methods({
    convert(input: string): number {
        return Number(input)
    }
})
...
function myFunctionExpectingStamp(obj: { convert: (string) => number }) {
    // everything is cool, the `obj.convert` is what we need
}
```

You can try here what is produced: https://codemix.github.io/flow-runtime/#/try

**Comment by ericelliott** [comment]
Flow mostly relies on structural type checks, which is like automatic duck typing. I think Flow uses nominal checks in some situations, which is bad and not like duck typing. TypeScript uses all structural checks, AFAIK.

**Comment by FredyC** [comment]
> Flow uses structural typing for objects and functions, but nominal typing for classes.
https://flow.org/en/docs/lang/nominal-structural/

These are new terms for me :) 

Anyway in the example above it's clearly a structural check, so it can be considered same thing as duck typing. From my understand the _duck typing_ is something like this, right ?

```js
function myFunctionExpectingStamp(obj) {
    if (!(obj && typeof obj.convert === 'function') {
        throw new Error('missing convert method');
    }
}
```

With static typing it looks much more clean, readable and reusable in my opinion. So my question could be: "Is duck typing obsolete?"
