### ISSUE TITLE
Performance issues with Object.create()

### ISSUE THREAD

**Issue by denyskoch** [ericelliott/stampit#49]
Hey, it looks like, creating objects with Object.create() and add properties is slow at initialization but also at accessing them later. See this post:
http://mrale.ph/blog/2014/07/30/constructor-vs-objectcreate.html

What do you think about ist and how stampit can/has solved this?

**Comment by ericelliott** [comment]
Object creation and property access are lightning fast no matter which technique you use. These are micro-optimizations. I've never seen an application where this is the bottleneck. Don't optimize this unless you've profiled your app and proven that it's a problem. Read [You're Optimizing the Wrong Things](http://ericleads.com/2013/04/youre-optimizing-the-wrong-things/).
