### ISSUE TITLE
Use lodash instead of mout

### ISSUE THREAD

**Issue by koresar** [ericelliott/stampit#51]
Since lodash v3.0 you can `require('lodash/object/merge')` exactly the same way as we do with mout.

Lodash is a bit faster, a bit smaller, uses a bit less memory.

Additionally, lodash has [`_.matches`](https://lodash.com/docs#matches) function which could be handy implementing #50.

Also lodash is under active development, have better online docs and JSDoc.

**Comment by ericelliott** [comment]
Absolutely agreed, and IMO should be a good thing to add to 2.0.

:+1:

**Comment by koresar** [comment]
Implemented with #63 and #60.
