### ISSUE TITLE
add stampit.getStampOf method

### ISSUE THREAD

**Issue by zaboco** [ericelliott/stampit#55]
It might be useful to add a method for getting the stamp of an instance (e.g. `stampit.getStampOf`)

Consider this use case: I want to add a `Cloner` mixin, which just adds a `clone` method to a stamp. I would like to write something like:
```js
var Cloner = stampit().methods({
  clone: function() {
    var stamp = stampit.getStampOf(this)
    return stamp(this)
  }
})
```

Right now, I have to do a mixin factory:
```js
var ClonerFactory = function(stamp) {
  return stampit().methods({
    clone: function() {
      return stamp(this)
    }
  })
}
```
But adding it as a mixin to another stamp is not straightforward:
```js
var SomeStamp = stampit()
  .state({ ... })
  .methods({ ... })

SomeStamp = SomeStamp.compose(ClonerFactory(SomeStamp))
```
instead of:
```js
var SomeStamp = stampit()
  .state({ ... })
  .methods({ ... })
  .compose(Cloner)
```

**Comment by koresar** [comment]
First of all, it is always interesting to understand why you need this?

Second, you what something similar to `instaceof`. Correct?

**Comment by zaboco** [comment]
Well, not really `instanceof`, more like `constructor`. I think it's useful to have access to the factory method of an instance, so you can create another similar instance (as in my example). But, if this is not in the spirit of the library, I can understand.

**Comment by ericelliott** [comment]
This seems really application specific, to me. The only use-case I can think of is to add a `.clone()` method to instances -- something you don't need if you have the stamp in-scope.

Your `.clone()` method is also a bit awkwardly named, because it doesn't create a clone of the current instance -- instead, it creates a fresh instance based on the stamp -- without the current instance's state.

Am I missing something that would make this more generally usable? Maybe specific use-cases? Why is the `.clone()` method you describe useful? Why not just use the stamp to create new instances, instead?

**Comment by koresar** [comment]
It is rather cheap to add one more reference per each stamp (aka prototype). I'd add this feature if I was the boss. :)

I believe I will start my own fork of stampit. Not because of this feature, but because we do not iterate fast enough. Several months is too much to apply a PR to a non-master branch. @ericelliott, I beg your pardon. But I would like step out as a co-maintainer of this module.

**Comment by ericelliott** [comment]
@koresar As a maintainer, you have the power to bring in other contributors to review your commits. You don't need to fork.

Don't wait around for me. Have a buddy review your commits and merge them in.

**Comment by zaboco** [comment]
@ericelliott I was thinking of cases when you don't have the stamp in scope (such as when getting an instance as a parameter in another function, in another module), and you don't want to mutate the received instance, instead you want to return a new instance.

My `.clone` method works, since it does `stamp(this)` which copies the state from `this` instance (and also any overridden methods).

Anyway, maybe I rushed a little, I should use the library more, so I can find a relevant use case. So far I've just played with it, and I really enjoy it.

**Comment by koresar** [comment]
I, actually, like the idea of having that function. There is little memory penalty, but, as Eric says, "this is not your bottleneck". :)

**Comment by unstoppablecarl** [comment]
I think something equivalent to setting a `constructor` property on a prototype in vanilla js would be very useful. The `.clone()` described has limited functionality as it doesn't give you direct access to the stamp and it copies overridden methods. Also the name clone is somewhat deceptive as it does not deep copy. I think it would be much more useful to have access to the stamp that created the object instance. Then you could check what stamp created the instance or create another instance using the same stamp.

I propose adding a `stamp` property with the same purpose as the `constructor` property commonly used in vanilla js (not sure exactly what the property key would be, maybe something stronger like '__STAMP__'). 

```js

var thing = stampit()
  .state({ ... })
  .methods({ ... })

var myThing = thing();

var myThingsStamp = myThing.stamp;

myThingsStamp === thing; // true

var myOtherThing = myThingsStamp();

// in the case of copying instance properties you could simply do

var myModifiedThing = myThingsStamp(myThing);

```

**Comment by koresar** [comment]
We are definitely not adding the 'stamp' property to each created object. That's an unexpected explicit behaviour which might and would lead to hidden bugs.

**Comment by unstoppablecarl** [comment]
Are there any alternative ways to figure out the stamp that created an object instance?

**Comment by koresar** [comment]
Nothing inbuilt, but there are many ways to implement it yourself for any particular stamp.

**Comment by ericelliott** [comment]
My $0.02 -- the programmer should have 100% control over what the stamp *creates*. If we can make it easier to add a `.getStamp()` method to the object instances, that's cool, but Stampit shouldn't add it to the instances directly.

**Comment by ericelliott** [comment]
> We are definitely not adding the 'stamp' property to each created object. That's an unexpected explicit behaviour which might and would lead to hidden bugs.

:+1:

**Comment by unstoppablecarl** [comment]
I can see the problems it would cause. I would be happy with any solution that lets you easily set a function that gets the stamp from the instance.

**Comment by koresar** [comment]
Maybe we should add an ES6 `Symbol('stamp')` to the prototype. Consider the following unit test:
```js
let myStamp = stampit();
let myObject = myStamp({ stamp: "this is a regular property" });

let stampSymbol = Object.getOwnPropertySymbols(myObject.prototype)[0];
assert(myObject[stampSymbol] === myStamp);
```

After that, we can implement `stampit.getStampOf(myObject)`. Something like this (I hope I got the syntax right).
```js
stampit.getStampOf = (obj) => {
  let symbols = Object.getOwnPropertySymbols(myObject.prototype);
  if (symbols.length === 1 && symbols[0] == "stamp") {
    return myObject[symbols[0]];
  }
};
```

**Comment by ericelliott** [comment]
I'm still getting familiar with ES6. Can you walk me through exactly what's going on in that code? I'm having trouble running it with Traceur: `TypeError: Cannot read property 'prototype' of undefined`

How would that compile back to ES5?

Of course we can't use features that won't compile back to ES5 for browser compatibility. =|

**Comment by ericelliott** [comment]
For this to work, we'd need to polyfill `.getOwnPropertySymbols` for browsers that don't support symbols, yet.

**Comment by koresar** [comment]
True. I have just thrown an idea. Other than symbol we could use a "very very hidden property" so to say. :)
```js
let myStamp = stampit();
let myObject = myStamp({ stamp: "this is a regular property" });

let stampSymbol = myObject.prototype.__stamp__;
assert(myObject[stampSymbol] === myStamp);
```

And then:
```js
stampit.getStampOf = (obj) => {
  let stamp = myObject.prototype.__stamp__;
  if (stampit.isStamp(stamp) {
    return stamp;
  }
};
```

**Comment by koresar** [comment]
update: heavily changed the comment above.

**Comment by unstoppablecarl** [comment]
This is exactly what I recommended and you said was not a good idea.

**Comment by ericelliott** [comment]
```
var stamp = myObject.prototype.__stamp__;
```

1. There is no `myObject.prototype` property unless you create one. [[Prototype]] is not a property on an instance. It is available on a constructor function, but Stampit doesn't use them.

2. Authors need full control over the object being created. We should not add properties to the object instances, hidden or otherwise. If the author wants to add a reference to the stamp, they can do so with `.enclose()`.

**Comment by koresar** [comment]
Let me workaround this. How about new utility method for each stamp?

```js
stamp.hasCreated = function (obj) {
  return obj.__proto__ === this.fixed.methods;
};
```

This should work as we are using the `fixed.methods` property as a prototype for objects. Eric?

**Comment by koresar** [comment]
Maybe we should make stamps "plugin-able". We can allow people to hook into the `function factory()`.

```js
var clonableStamp = stampit("stampit");
clonableStamp.on("ctreated", function (obj, stamp) {
  obj.clone = function () { return stamp(obj); }
});

// and usage
var myShinyStamp = stampit({ whatever: 42 });
var myShinyClonableStamp = myShinyStamp.compose(clonableStamp); // merges 'on()' events
var myShinyObject = myShinyClonableStamp();
var IAmClone = myShinyObject.clone(); // we have clone() method in each object!
assert(IAmClone.whatever === 42);
```

**Comment by koresar** [comment]
@zaboco You can workaround current stampit limitations by hacking the `stamp.fixed` object.

```js
function makeClonable(stamp) {
  stamp.fixed.methods.clone = function () { return stamp(this); };
}

// and usage
var SomeStamp = makeCloneable(stampit({ /*state*/ }, { /*methods*/ }));
```

**Comment by ericelliott** [comment]
Maybe we should make stamps "plugin-able". We can allow people to hook into the `function factory()`.

```js
var clonableStamp = stampit();
clonableStamp.on("ctreated", function (obj, stamp) {
  obj.clone = function () { return stamp(obj); }
});

// and usage
var myShinyStamp = stampit({ whatever: 42 });
var myShinyClonableStamp = myShinyStamp.compose(clonableStamp); // merges 'on()' events
var myShinyObject = myShinyClonableStamp();
var IAmClone = myShinyObject.clone(); // we have clone() method in each object!
assert(IAmClone.whatever === 42);
```

All the suggestions so far have sounded pretty ugly to me. Lifecycle hooks are much better, but how is this different from `.enclose()`? You get `stamp()` passed in?

**Comment by koresar** [comment]
Yes. We got both stamp and the created object in the same function scope.

The `function factory()` is closed from an outside intrusion, but it is the only place where we have access to both stamp and object.

**Comment by ericelliott** [comment]
I see, and we can't just pass the stamp into `.enclose()` functions because we pass the args in. We should have just passed an options object in. My bad.

I'm cool with it if you want to add a `created` lifecycle hook, but I think we should pass a named options hash into it and deprecate `.enclose()` (the name confuses people anyway).

Basically make it the flexible method that `.enclose()` should have been. =)

Named options:

* **instance**
* **stamp**
* **args**

Thanks to ES6 destructuring, using them is almost as convenient as using formal params:

```js
function foo ({ param1, param2, param3}) {
  console.log(param1, param2, param3);
}

foo({param1: 'foo', param2: 'bar', param3: 'baz'}); // logs foo bar baz
```

This way we leave the created hook open for extension like `.enclose()` should have been. ;)

Thoughts?

**Comment by ericelliott** [comment]
I suppose we could also still make `instance` available as `this`.

**Comment by unstoppablecarl** [comment]
I think `init` or `initialize` would be a good names. Technically the `refs` and `props` are for initializing as well but this is where initialization code would go right?

**Comment by koresar** [comment]
Eric, I was thinking of this solution but was afraid to break backwards compatibility. Although, the `enclose()` arguments is a rather new feature. There should be few people using it.

`init()` would be the good name for the new alias.

`this` and `instance` should be both available IMO.

**Comment by unstoppablecarl** [comment]
I am not sure if a full event system is necessary. What cases other than `created` are there? 

A very simple solution would be:

```js
// .init() aka .enclose()
var stamp = stampit().init(function(settings, stamp){ });
```
This would break backward compatibility though. I don't remember if it was decided to make the factory args a settings hash or not.

**Comment by koresar** [comment]
Ok, let's implement the Eric design in v2_0.

**Comment by ericelliott** [comment]
My logic for avoiding `.init()` in the first place was that users might think that's *the way* to define initialization logic, and I was hoping we could train users to separate instantiation from initialization more. For example, my favorite way to initialize private vars is this:

```js
var f = stampit().enclose(function() {
  var name;

  return stampit.mixIn(this, {
    // Getter and setter for name:
    name: function (value) {
      if (value) {
        name = value;
        return this;
      }
      return name;
    }
  });
});

// f() instantiates and returns the instance.
// .name('foo') initializes the private variable.
var thing = f().name('foo'); 
thing.name(); // 'foo'
```

Note that the initialization doesn't actually happen until you call the instance's `.name()` method.

Maybe I was wrong, though, because `.enclose()` does seem to confuse users a lot more than I anticipated. );

**Comment by ericelliott** [comment]
So we don't have to deprecate yet another method, I'm going to insist that we pass an options hash *instead of a list of formal params*:

## NOT THIS

```js
var stamp = stampit().init(function(settings, stamp){ });
```

## Ah, this is better...

```js
var stamp = stampit().init(function({instance, stamp, args}){ });
```

## In ES5...

```js
var stamp = stampit().init(function(options){ /* instance, stamp, and args are available on options obj */});
```

**Comment by koresar** [comment]
I've created #62 to address this. Eric, feel free to *edit* #62. Whatever name the enclose-init would have I agree to any one.

IMO, `init` is a good name because this is actually what it's for - initialization of an instance. But, again. I'm happy with any name.

**Comment by koresar** [comment]
@zaboco I will close this issue as we are going to implement #62. Please, feel free to open a new one if necessary.

**Comment by zaboco** [comment]
@koresar ok, #62 sounds nice
