### ISSUE TITLE
Add travis-ci

### ISSUE THREAD

**Issue by ericelliott** [ericelliott/stampit#56]
We should have Travis-ci badge and GitHub connection. Don't worry about Sauce Labs for this. Just have it run tests on Travis machines.

Ping me after the `travis.yml` file is ready and I'll make sure the GitHub integration works.

**Comment by koresar** [comment]
What's "local tests"? I run the tests locally by opening a html page. Do you mean something like `npm test` which would run `mocha` or something?

**Comment by ericelliott** [comment]
There are a couple options:

1. Port the tests to [tape](https://github.com/substack/tape)
2. Keep the QUnit suite and use [phantomjs](http://phantomjs.org/) to get the test results.

Option 1 is probably best, but we'll need to bundle the test scripts for browsers so we can still run them on Sauce Labs, too.

**Comment by ericelliott** [comment]
Check out [tape-run](https://github.com/juliangruber/tape-run)

**Comment by koresar** [comment]
:+1:

**Comment by koresar** [comment]
I've split out issue #61. Let this one be travis only .

**Comment by koresar** [comment]
@ericelliott please connect stampit to Travis-CI.
It will run on every push for every branch.

Thanks!

**Comment by ericelliott** [comment]
Done. :+1:

**Comment by koresar** [comment]
It works!
