### ISSUE TITLE
Deep cloning state for v2.0

### ISSUE THREAD

**Issue by koresar** [ericelliott/stampit#57]
1. New `.refs()` method for stamps which should shallow copy references.
1. `state()` should be deprecated (in docs, not in code yet) in favour of new `refs()`. `state()` should be v1.x compatible. `state()` will essentially be an alias to `refs()`.
1. New `props()` methods should deep clone the given object(s).

**Comment by ericelliott** [comment]
:+1:

**Comment by koresar** [comment]
You reckon we should add fourth parameter to the 'stampit' function to accept deep cloned "props" object? @ericelliott

**Comment by ericelliott** [comment]
Yes.

**Comment by koresar** [comment]
@ericelliott Should I add the "refs" to the prototype, or to the object itself (as it is now)?

I'm asking that because "props" are definitely are going to be merged to the object itself. But they might conflict with "refs". (I hope I'm clear here.)

**Comment by koresar** [comment]
On the other hand, adding "state" values to prototype might break someone's code.

**Comment by koresar** [comment]
Yeah, definitely the "state" (aka "refs") should go to each stamp. Discussion is over. :))))))

**Comment by koresar** [comment]
One more thing I am hesitating about. The `stamp(obj)` should deep merge the `obj` or shallow mix in the properties?

**Comment by koresar** [comment]
JFYI: It's shallow mixed-in in stampit@1.1.

poke @ericelliott

**Comment by unstoppablecarl** [comment]
I think it should shallow merge. I don't think you would need to deep clone for init.

**Comment by ericelliott** [comment]
> On the other hand, adding "state" values to prototype might break someone's code.

:+1: 

> The stamp(obj) should deep merge the obj or shallow mix in the properties?

I think shallow is better for 2 reasons: 

1. It's not a breaking change
2. It's probably less surprising behavior

**Comment by unstoppablecarl** [comment]
Also: if you do need to make a clone you can do that before passing it in, or as part of your factory code. If it clones by default and you need to set by ref, you just can't.

**Comment by koresar** [comment]
All the good reason. Thanks, guys.
I'd need to update PR #60 then. I'll ping you when it's ready for review.
Cheers.

**Comment by koresar** [comment]
#60 was implemented and merged to v2_0 branch. Closing this issue.
