### ISSUE TITLE
Provide options for satisfying stampit's dependencies

### ISSUE THREAD

**Issue by sethlivingston** [ericelliott/stampit#59]
Give stampit users different options to satisfy its dependency on lodash/mout/underscore functions (the _ functions). My initial thought is to create separate builds:

1. stampit with the _ functions bundled - no dependencies listed in package.json.
2. stampit with a dependency on lodash.
3. stampit with dependencies on the individual lodash function modules.
4. stampit with a dependency on underscore.

Options 2-4 shouldn't have those functions/libraries bundled--just listed as dependencies.

**Comment by ericelliott** [comment]
Really? Are you hoping to use this for a planned production deployment, or just floating the idea?

Lodash dependencies bundled is really inexpensive...

**Comment by koresar** [comment]
JFYI.
`stampit.min.js` size in `v2_0` is currently 32879 bytes. Whereas, stampit@1.1 same file size is 7000 bytes.
But that's maybe irrelevant.

**Comment by sethlivingston** [comment]
Yes I'm using this for a production app under development. For me, a dependency on lodash is fine, but I don't want it bundled inside stampit (and can't imagine others would, either).

But yes I was also just floating the idea.

**Comment by koresar** [comment]
Your 'lodash' will be reused if stampit targets the same version as you (`^3.8.0`). That's how NPM works.

**Comment by sethlivingston** [comment]
Yep, that's what I meant. I think we're on the same page.

**Comment by koresar** [comment]
The proposed feature is rather complicated to build. There is human resource shortage at the moment. The cake is not worth the effort IMO.

However, as always, PR's are very welcome!

Closing this issue as `won't fix`. I hope that's okay with you @sethlivingston.

**Comment by sethlivingston** [comment]
Understandable.

**Comment by ericelliott** [comment]
You don't need this feature. Browserify and Webpack automatically dedupe if you already have the same lodash version in your bundle.
