### ISSUE TITLE
tape-run with pantomjs does not show unhadled exceptions

### ISSUE THREAD

**Issue by koresar** [ericelliott/stampit#70]
1. Make a typo in a test (like `enclos` instead of `enclose`).
1. Run `npm test`.
Expected: an error text saying something like `Uncaught TypeError: stampit(...).enclos is not a function`
Actual: the process freezes forever.

Interestingly, but if I use chrome (`tape-run -b chrome`) everything works as expected.

@JosephClay any ideas? Can you test it, and maybe even fix?

**Comment by koresar** [comment]
But even if you see the error message, you won't see the stack trace. Am I doing something wrong?

I miss stack trace very much. It is really a time-consuming job if you don't have an exception call stack. :(

**Comment by koresar** [comment]
In fact, simple `node test/stampit-specs.js` runs tests smoothly even without phantomjs.

I might not know something. But would someone explain me why we need phantomjs to run tests locally?

**Comment by troutowicz** [comment]
I have experienced the same problems with tape-run/phantomjs. But yeah, there really is no need for stampit tests to be ran in a browser. I'm just executing tests directly over at [react-stampit](https://github.com/troutowicz/react-stampit).

**Comment by ericelliott** [comment]
Let's skip phantomjs. If we want to test in-browser, we should just use Sauce Labs.

You should get all your errors if you run tape without Stampit. Does that work for you?

**Comment by JosephClay** [comment]
Testing locally, if I force a test to fail, I'm seeing:
```
# tests 114
# pass 113
# fail 1
```
It does hang on a TypeError. Not sure why.

**Comment by koresar** [comment]
There are 171 tests in the `init-making-stampit-flexible` branch. Which is soon to be merged into `v2_0`. I've removed support there. So, as soon as in 12 hours all the issues mentioned here will be resolved. :)

**Comment by ericelliott** [comment]
:+1:

**Comment by koresar** [comment]
The issue got resolved in branch 2.0 with `node test/index.js` instead of `tape-run`. :)

I confirm exception stack traces are being printed. Tape assertions print the file name and line number on fails.

All good.
