### ISSUE TITLE
Update README to reflect changes in v2.0

### ISSUE THREAD

**Issue by koresar** [ericelliott/stampit#71]
A list of things to mention:
* [x] New aliases (`refs`, `init`).
* [x] New `props` method and fourth argument to `stampit()`. The way it works.
* [x] Immutable stamps (chaining always creates new stamp).
* [x] The way (init (aka enclose) works - `{instance, stamp, args}`.
* [x] Short list of breaking changes...
* [x] Two examples (`clone` and `getStamp`) from #62 as code samples.
* [x] New core stampit API (`stampit({methods, refs, init, props }`).
* [x] New `static` feature.
* ...

**Comment by ericelliott** [comment]
:+1:

**Comment by koresar** [comment]
Everyone, who has write access, are welcome to edit the new README. Here is the direct link:
https://github.com/ericelliott/stampit/edit/README_v2_0/README.md

I encourage you to do it because, as you might have noticed, my English skill sometimes lack proper structure.

**Comment by unstoppablecarl** [comment]
I think there needs to be something explaining that `stampit().init()` can be used to enclose private data and as an initializer/constructor. I am not sure where this should go though.

**Comment by koresar** [comment]
How about #81?

**Comment by koresar** [comment]
Okay.

The PR #83 is ready to be reviewed and merged into v2. Waiting for Eric for a day.

Thanks you people for collaboration. It is so joyful to know I'm not alone. :) Cheers!

**Comment by unstoppablecarl** [comment]
There is a lot of content needed to fully explain and document `stampit`. I think the current readme has too much for one file. 
I propose:
 - README.md description, table of contents type list of links to other info, very basic code examples with links to more in depth descriptions/examples of methods in other files or wiki pages
 - examples.md/wiki in depth examples and explanations of methods and specific cases see #81 
 - api.md the api section of the README.md

@koresar if you can get on gitter I would like to discuss.

**Comment by koresar** [comment]
* Would you do that the way you see it, please?
* I'm okay with any number of .md files, but I'm strongly against dev. docs in wiki. I usually open `node_modules/module/README.md` instead of going only for API documentation. Wiki is good for  non-development info (like proposals, drafts, or history tracking).
* :+1:

**Comment by ericelliott** [comment]
* fourth argument to stampit()

Didn't we decide that we're switching to an options object in 2.0?

I don't want 5 arguments in the API.

I know this is a breaking change, but it's 2.0. This is our chance to improve the API. I'm more concerned about making sure that we can still *compose with 1.x stamps*, but I don't think we need the same API to create new stamps.

**Comment by koresar** [comment]
Yes, Eric. We did. It'll be implemented as a non-breaking change to the 2.x line. Say in 2.1. Ok?

**Comment by ericelliott** [comment]
How could it be a non-breaking change?

**Comment by koresar** [comment]
I kind of hoped we can ducktype the first argument. Do you think that's feasible?

**Comment by ericelliott** [comment]
I really think that's a bad idea. We've got a whole lot of reserved names that could collide with stamp properties.

:frowning:

**Comment by ericelliott** [comment]
I think it's cool to do it in a different commit, but we can't cut a 2.0 release until the signature is finalized.

**Comment by koresar** [comment]
Eric, I am getting confused...

1) We were talking that compatibility with 1.x is what we should look at while releasing stampit v2.
2) Now you are saying "break the stampit main API".

We have to select one of the two paths: try to have as less as possible differences with stampit v1 API, or break most of the stampit v1 API's.

You should keep in mind that options object implementation #73 will take weeks.

**Comment by ericelliott** [comment]
Break the function signature (so we can fix it).

Preserve compatibility with 1.x stamps.

**Comment by ericelliott** [comment]
Here's an easy rule of thumb:

What's *right for our users* is more important than *what's convenient for us*.

**Comment by unstoppablecarl** [comment]
Breaking this will have little consequence as I think few people used it in 1.x anyway. If someone was using this the arguments in 1.x it would be pretty painless to adapt to the new api anyway.

**Comment by troutowicz** [comment]
> If someone was using this the arguments in 1.x it would be pretty painless to adapt to the new api anyway.

:+1:

**Comment by koresar** [comment]
Please, review #84.

If anyone could update the README using the link above to reflect the changes that would be very helpful. The list of changes you can find in #84.

Thank you, my future helper!

**Comment by koresar** [comment]
Thank @ericelliott for merging. Although, the README still lack `static` descriptions, examples, and the rest. See the checkboxes on top. :)

**Comment by koresar** [comment]
@ericelliott you've committed the merge conflict! 
https://github.com/ericelliott/stampit#and-init-

**Comment by ericelliott** [comment]
Yep, I noticed. Let's keep this issue open until that's done. I wanted some 2.0 documentation so others can start testing from repo clones. :)

**Comment by koresar** [comment]
The README is up to date. [Дякую](https://translate.google.com.au/?ie=UTF-8&hl=en&client=tw-ob#uk/en/%D0%B4%D1%8F%D0%BA%D1%83%D1%8E)!

P.S. Someday a better structured one(s) should be written IMO.
