### ISSUE TITLE
grouping stampit arguments list

### ISSUE THREAD

**Issue by koresar** [ericelliott/stampit#73]
Add an option to create stamps in the following way:
```js
var stamp = stampit({
  refs: {},
  methods: {},
  init: function () {}, // or an array of functions
  props: {}
});
```

**Comment by troutowicz** [comment]
We should deprecate the current arg format in favor of this... too much code smell.

**Comment by ericelliott** [comment]
:+1: 

Absolutely. Named properties only for stamp creation in v2. No more multi-arg support.

We should keep the fluent methods, though. =)

**Comment by koresar** [comment]
We should keep in mind that we want to have as much compatibility with v1
as possible. Just reminding. :-)

**Comment by ericelliott** [comment]
Agreed, but I think a lot of people are using the fluent methods instead of the arg list, anyway, just because it's a more direct way of building the stamp they want.

**Comment by ericelliott** [comment]
Just to clarify, we can't put this off for 2.1 because it's a breaking change. If we do a 2.0 release before this is done, this would have to be 3.0, not 2.1 -- and that's awkward because users may worry that our API is too unstable to rely on.

We need to balance evolving user needs and  API stability. I think the best way to do that is to ship this change with 2.0.

**Comment by dcollinsf5** [comment]
I agree. Even though I used the args list method for all of my stamps... Since upgrading to 2.0 will require a code audit anyway, I'd really like to get any syntax conversions out of the way at the same time.

**Comment by koresar** [comment]
I don't mind implementing the feature. It would take much time since there are many unit test to adjust.

I'll do that over the weekend. But strict review would be necessary.

**Comment by troutowicz** [comment]
It's worth the effort. :)

**Comment by ericelliott** [comment]
:+1:

**Comment by koresar** [comment]
Please review #84. After the merge I'm closing this issue. Cheers :)

**Comment by koresar** [comment]
Implemented!
Thanks everyone. That was a great journey. :) Get ready for the next episodes.
