### ISSUE TITLE
Add new static() method to stamps

### ISSUE THREAD

**Issue by koresar** [ericelliott/stampit#74]
Depends on #73.

The following should add properties to stamps (not objects).
```js
var stamp = stampit({ static: { myProp: "prop value" } });
assert(stamp.myProp === "prop value");

var anObject = {};
var stamp2 = stamp.static({ secondProp: anObject });
assert(stamp2.secondProp === anObject);
```

**Comment by troutowicz** [comment]
:+1:

**Comment by ericelliott** [comment]
Fixed `assert()` ;)

:+1:

**Comment by koresar** [comment]
Stampit must warn users if they are using "reserved" stampit names: create, methods, refs, state, init, enclose, compose, statics, and fixed.

**Comment by koresar** [comment]
How would a code detect if the stampit is running in the **debug mode**? @ericelliott ?

**Comment by ericelliott** [comment]
Could be as simple as:

```
import debug from `./debug`
```

We could use a build step to write `export default true` or `export default false` from that file depending on which build is running at the moment.

Then you could do `if (debug)` checks before warning.

**Comment by koresar** [comment]
Done with #84
