### ISSUE TITLE
.refs() (a.k.a. .state() ) vs .props() in Stampit v2

### ISSUE THREAD

**Issue by dwiyatci** [ericelliott/stampit#94]
Hey guys, =)

currently I'm using Stampit v1.x in my development system (and about to push it to the production), and I recently read about Stampit v2. I know that `.refs()` is the new name for `.state()`, but I'm not sure whether my understanding of `.props()` is quite right.

Isn't it `.props()` just `.refs()` with Boolean flag `deep` (recursively merge) set to **true**? Are there other use cases for it? I mean, I just got used to `.state()`, and so why bother to split `.state()` into these two methods in the first place?

Cheers

**Comment by troutowicz** [comment]
@koresar can correct me if I am wrong, but I believe `props` is really what `state` used to be and `refs` is replacing the previously known behavior of `state`. `refs` data is a shallow copy, `props` is a deep merge.

**Comment by unstoppablecarl** [comment]
Correct. `refs` assigns values "by reference" and `props` makes a deep copy. `props` is more for initializing properties with things like objects or arrays that you want to be unique to each object instance.

**Comment by koresar** [comment]
@troutowicz correct. `refs` is for shallow copying, and `props` is for deep clone/merge.

In stampit v1 the `state` behaved like `refs` (most of the time though). So, @dwiyatci, with you should v2 continue using `state` as you were using in before with v1. `props` is a handy method for a very rare occasion.

This comment explains how stampit v1 works: https://github.com/ericelliott/stampit/issues/40#issuecomment-69848225

**Comment by dwiyatci** [comment]
Got it. Thanks a lot guys! =)

**Comment by unstoppablecarl** [comment]
I just want to clarify for future reference. 

`refs()` is equivalent to `_.extend()` https://lodash.com/docs#assign
`props()` is equivalent to `_.cloneDeep()` https://lodash.com/docs#cloneDeep

**Comment by koresar** [comment]
To be more correct, "props" is equivalent to "merge" (which also deeply
clones if the destination object is empty).

**Comment by lwhorton** [comment]
I found this confusing when it cropped up in a project... so to prove it to myself I wrote up a quick spec. Hope this helps someone else too:

```javascript
var stampit = require('stampit')
    , chai = require('chai')
    , expect = chai.expect

chai.should()

describe('testing stampit', function() {
    var sut
    describe('when using refs', function() {
        var stamp
        beforeEach(function () {
            var refs = {
                a: 'is a'
                , b: {}
                , c: {
                    nestedObject: {}
                }
            }
            stamp = stampit()
                .refs(refs)
        })
        it('should not reference the same atom across multiple instances', function() {
            var one = stamp.create()
            var two = stamp.create()
            one.a = 'is another a'
            two.a.should.equal('is a')
        })
        it('should reference the same object across multiple instances', function() {
            var one = stamp.create()
            var two = stamp.create()
            one.b.cat = true
            two.b.cat.should.equal(true)

            two.b.dog = true
            one.b.dog.should.equal(true)
        })
        it('should reference the same nested object across multiple instances', function() {
            var one = stamp.create()
            var two = stamp.create()
            one.c.nestedObject.cat = true
            two.c.nestedObject.cat.should.equal(true)

            two.c.dog = true
            one.c.dog.should.equal(true)

            two.c.nestedObject.dog = true
            two.c.nestedObject.dog.should.equal(true)
        })
    })
    describe('when using props', function() {
        var stamp
        beforeEach(function () {
            var props = {
                a: 'is a'
                , b: {}
                , c: {
                    nestedObject: { }
                }
            }
            stamp = stampit()
                .props(props)
        })
        it('should reference a different atom across multiple instances', function() {
            var one = stamp.create()
            var two = stamp.create()
            one.a = 'is another a'
            two.a.should.equal('is a')
        })
        it('should reference a different object across multiple instances', function() {
            var one = stamp.create()
            var two = stamp.create()
            one.b.cat = true
            expect(two.b.cat).to.be.undefined

            two.b.dog = true
            expect(one.b.dog).to.be.undefined
        })
        it('should reference a different nested object across multiple instances', function() {
            var one = stamp.create()
            var two = stamp.create()
            one.c.nestedObject.cat = true
            expect(two.c.nestedObject.cat).to.be.undefined

            two.c.dog = true
            expect(one.c.dog).to.be.undefined

            two.c.nestedObject.dog = true
            expect(one.c.nestedObject.dog).to.be.undefined
        })
    })
})
```

**Comment by koresar** [comment]
@lwhorton Thanks mate!
Here are few more: 
* https://github.com/stampit-org/stampit/blob/master/test/basics-refs.js
* https://github.com/stampit-org/stampit/blob/master/test/basics-props.js

And many more here: https://github.com/stampit-org/stampit/tree/master/test
