### ISSUE TITLE
If I'm introducing Stampit to a project today, should I use v1 or v2?

### ISSUE THREAD

**Issue by mark-rushakoff** [ericelliott/stampit#95]
The README leads me to believe I should be using v2, but `npm install stampit` installs a v1 version.

**Comment by troutowicz** [comment]
v2 is expected to officially land this weekend. I would suggest becoming familiar with the new API of v2.

**Comment by koresar** [comment]
Cheers @mark-rushakoff 
I'm closing this issue. I hope you're okay with that.

**Comment by ericelliott** [comment]
I should probably release a v2 release candidate on npm to make it easier to use v2, but you should be aware that v2 is still a little bit in flux, and there could be bug fixes in the v2 line that may change some of its current behavior in a way that could be a breaking change.
